# Generated by Django 3.0.12 on 2021-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to='rooms.Room'),
        ),
    ]
